apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 2
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: colecrtr/website:7597280b85ad85dd1c456f06b16e8d5d3c162e95
        ports:
          - containerPort: 80
